// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbzevO1cDwZLA1bvbKmsbCaNWaI63s8N4',
    appId: '1:553491692617:web:66f0b7e496571263319398',
    messagingSenderId: '553491692617',
    projectId: 'izdavanjestanova-c6772',
    authDomain: 'izdavanjestanova-c6772.firebaseapp.com',
    storageBucket: 'izdavanjestanova-c6772.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmPPC64sfuqn1iaebvZDhS31SEjc1ZxpA',
    appId: '1:553491692617:android:39eb1e37b612bb58319398',
    messagingSenderId: '553491692617',
    projectId: 'izdavanjestanova-c6772',
    storageBucket: 'izdavanjestanova-c6772.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCHFHue7mFa5cZ4L8lVazJHCEMJ2YGXRE',
    appId: '1:553491692617:ios:88f214643e222e1c319398',
    messagingSenderId: '553491692617',
    projectId: 'izdavanjestanova-c6772',
    storageBucket: 'izdavanjestanova-c6772.firebasestorage.app',
    iosBundleId: 'com.example.stanoviApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCHFHue7mFa5cZ4L8lVazJHCEMJ2YGXRE',
    appId: '1:553491692617:ios:88f214643e222e1c319398',
    messagingSenderId: '553491692617',
    projectId: 'izdavanjestanova-c6772',
    storageBucket: 'izdavanjestanova-c6772.firebasestorage.app',
    iosBundleId: 'com.example.stanoviApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbzevO1cDwZLA1bvbKmsbCaNWaI63s8N4',
    appId: '1:553491692617:web:1a8bda11f5f2a980319398',
    messagingSenderId: '553491692617',
    projectId: 'izdavanjestanova-c6772',
    authDomain: 'izdavanjestanova-c6772.firebaseapp.com',
    storageBucket: 'izdavanjestanova-c6772.firebasestorage.app',
  );
}
